[package]
name = "multiplayer_serv"
version = "0.1.0"
authors = ["sirkibsirkib <christopher.esterhuyse@gmail.com>"]

[dependencies]
clap = "2.26.2"
piston_window = "0.70.0"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.4"
rand = "0.3"
